---
title: "analysis"
author: "Joyce Lee"
date: "03/05/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(lubridate)
library(tidyverse)
```

### Data wrangling

```{r}
driver_info <- read_csv("data/Driver_Info.csv")
incidents <- read_csv("data/Incidents.csv")
nswshifts <- read_csv("data/NSWshifts.csv") %>%
  distinct()
melbourneweather <- read_csv("data/melbourneweather_20150101_20210428.csv")
sydneyweather <- read_csv("data/sydneyweather_20150101_20210415.csv")
```

```{r}
incidents <- incidents %>%
  unite(EmployeeID, c("company", "EmployeeNumber"), remove = FALSE)
```

```{r}
nswshifts$VdsCompany <- toupper(nswshifts$VdsCompany)
nswshifts <- nswshifts %>%
  unite(EmployeeID, c("VdsCompany", "VdsEmployeeId"), remove = FALSE) 

library(data.table)
setDT(incidents)
setDT(nswshifts)
rhs_join <- incidents[nswshifts, 
                .(i.EmployeeID, x.DateOccurred, i.VdsTripStartTime, 
                  i.VdsTripEndTime),
                on = .(EmployeeID = EmployeeID, DateOccurred >= VdsTripStartTime,
                       DateOccurred <= VdsTripEndTime)][,.(EmployeeID = i.EmployeeID, DateOccurred = x.DateOccurred,
    VdsTripStartTime = i.VdsTripStartTime,
    VdsTripEndTime = i.VdsTripEndTime)]

lhs_join <- nswshifts[incidents, 
                .(i.EmployeeID, DateOccurred, x.VdsTripStartTime,
                  x.VdsTripEndTime),
                on = .(EmployeeID = EmployeeID, VdsTripStartTime <= DateOccurred,
                       VdsTripEndTime >= DateOccurred)][,.(EmployeeID = i.EmployeeID, DateOccurred = DateOccurred,
    VdsTripStartTime = x.VdsTripStartTime,
    VdsTripEndTime = x.VdsTripEndTime)]

test <- full_join(rhs_join, lhs_join) %>%
  left_join(incidents, by = c("EmployeeID", "DateOccurred")) %>%
  left_join(nswshifts, by = c("EmployeeID", "VdsTripStartTime", "VdsTripEndTime")) %>%
  left_join(driver_info, by = "EmployeeID")

test %>%
  mutate(occurredhour = hour(test$DateOccurred)) %>%
  mutate(midnight = case_when(occurredhour %in% c(23, 0, 1) ~ "yes",
                              occurredhour %in% c(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22) ~ "no")) %>%
  count(midnight)


tmp <- incidents %>%
  unite(EmployeeID, c("company", "EmployeeNumber"), remove = FALSE) %>%
  filter(company == 'TDNSW') %>%
  select(ClaimNumber, EmployeeID,TypeOfClaimName,DateOccurred) %>%
  mutate(JoinDate = as.Date(DateOccurred)) %>%
  left_join(nswshifts %>%
              mutate(JoinDate = as.Date(VdsTripStartTime)),
            by = c("EmployeeID","JoinDate")) %>%
  mutate(match_type = case_when(
    is.na(VdsTripStartTime) ~ 0,
    DateOccurred >= VdsTripStartTime & DateOccurred <= VdsTripEndTime ~ 2,
    TRUE ~ 1
  ))
matched <-
  tmp %>%
  inner_join(
    tmp %>% group_by(ClaimNumber) %>% summarise(match_type = max(match_type)),
    by = c("ClaimNumber", "match_type")
  ) %>%
  arrange(match_type,ClaimNumber,VdsTripStartTime)

tmp2 <- incidents %>%
  unite(EmployeeID, c("company", "EmployeeNumber"), remove = FALSE) %>%
  filter(company == 'TDNSW') %>%
  select(ClaimNumber, EmployeeID,TypeOfClaimName,DateOccurred) %>%
  mutate(JoinDate = as.Date(DateOccurred)) %>%
  left_join(nswshifts %>%
              mutate(JoinDate = as.Date(VdsTripStartTime)) %>%
              group_by(EmployeeID, JoinDate) %>%
              summarise(shift_start = min(VdsTripStartTime)-30*60,
                        shift_end = max(VdsTripEndTime)+30*60),
            by = c("EmployeeID","JoinDate")) %>%
  mutate(match_type = case_when(
    is.na(shift_start) ~ 0,
    DateOccurred >= shift_start & DateOccurred <= shift_end ~ 2,
    TRUE ~ 1
  ))
matched <-
  tmp2 %>%
  inner_join(
    tmp2 %>% group_by(ClaimNumber) %>% summarise(match_type = max(match_type)),
    by = c("ClaimNumber", "match_type")
  ) %>%
  arrange(match_type,ClaimNumber,shift_start)
```

```{r}
data.frame(t(melbourneweather[,c("lat", "lon", "asl", "variable", "unit", "level", "resolution", "aggregation", "timestamp")]))
data.frame(t(melbourneweather))

transpose(melbourneweather[1:7])
a <- melbourneweather %>%
  slice(1:8) 
as.data.frame(transpose(a, keep.names = "rn"))

as.data.frame(x = t(melbourneweather), stringsAsFactors = FALSE)
setNames(data.frame(t(melbourneweather[,-1])), melbourneweather[,1])

dcast(melt(melbourneweather, id.vars = "location"), location ~ "Melbourne")

melbourneweather %>%
  slice(1:8) %>%
  pivot_wider(id_cols = location, names_from = location, values_from = Melbourne:Melbourne_5)

melbourneweather %>%  
pivot_longer(names_to = c(Melbourne:Melbourne_5), values_to = location)
  pivot_wider(names_from = location, values_from = c(Melbourne:Melbourne_5)) %>%
  pivot_longer(names_to = timestamp, values_to = c(Melbourne_20150101T0000:Melbourne_20210428T2300))
```
